### ISSUE TITLE
Have v16 features been implemented?

### ISSUE THREAD

**Issue by adamblais** [esimiele/VMAT-TBI-CSI#12]
Hello, have v16 features been implemented? For example, setting the base dose plan in code. I ask because we have compiled the script using the v16 libraries, but we see the message "More features coming in v16!" Not sure if we made an error compiling the v16 plugin.

**Comment by esimiele** [comment]
No, all code was developed and tested using v15.6 of Eclipse. So the code was primarily targeted towards that version of ESAPI. The improvements with v16 should be relatively minor including building a plan setup with ESAPI, adding setup fields, setting a plan as a base dose plan, etc. I might do that in the future, but for now the code is targeted towards v15.6 of ESAPI. It will definitely still work on v16 of Eclipse. Nope, no errors on your end. That's a legacy message from the VMAT TBI autoplanning code (copied from that project). If you let me know what features you're interested in for v16, I can work with you and show you where to implement those pieces of code into the codebase

**Comment by crcrewso** [comment]
@adamblais One of the V16+ features I've been waiting to try is using multiple energies with one optimization. Is this something your clinic might explore?

**Comment by adamblais** [comment]
@esimiele Thanks for the offer! We're still early on in testing, but the goal would be to automate as much as we can, so setting plan orientation on AP/PA plans, setting base dose plan, and autoplanning for AP/PA would be of interest. We do have a programmer in house that might be able to implement these and share a fork.

@crcrewso Unfortunately, our clinic currently only has 6X VMAT commissioned (and 6FFF and 10FFF) so I don't think we will be exploring that in the foreseeable future.

**Comment by esimiele** [comment]
Sounds good. Let me know when you get to the point when you guys want to change things and I'd be happy to help if necessary.  Haha we have not experimented with multi-energy optimization. No idea if it will help or not

**Comment by adamblais** [comment]
What would be the best way to get in touch with you? Our programmer is looking at adding v16 features and could use some guidance on where to put the new code. Thanks!

**Comment by esimiele** [comment]
email primarily and possibly a zoom call depending on the complexity of what you want to implement. 
easimiele@uabmc.edu
