### ISSUE TITLE
Terminated unexpectedly in Optimization Loop

### ISSUE THREAD

**Issue by adamblais** [esimiele/VMAT-TBI-CSI#19]
I'm getting a crash during the optimization loop. For planning, I performed these steps:

- Ran through all steps in the planning script
- Set orientation of legs plan to feet first supine
- Calculated dose on legs plan
- Set legs as base plan for the VMAT plan optimization
- Saved
- Ran optimization loop

Screenshots of the error and the dump file. There is also a screenshot of the optimization loop progress window at the time of the crash.

[VMATTBICSIOptLoopMT.exe_270923_120857.txt](https://github.com/esimiele/VMAT-TBI-CSI/files/12741896/VMATTBICSIOptLoopMT.exe_270923_120857.txt)
![error](https://github.com/esimiele/VMAT-TBI-CSI/assets/144953440/f8a19fc4-89a6-4c88-af81-b371adff028f)
![progress](https://github.com/esimiele/VMAT-TBI-CSI/assets/144953440/5d8265ef-a43f-4ba9-b7fb-a4c60fedf99b)

**Comment by esimiele** [comment]
Interesting. The Varian log file isn't that useful unfortunately. From the progress window, it looks like it is failing on the second cropping operation and not making it to the point of recalculation. The easiest way to directly see the error is to run the optimization loop through visual studio. When you launch VMATTBICSIOptLoopMT in visual studio, it will show you all the recent patients that were planned using the prep script. Select your patient and try running and let me know what the error is. Unfortunately, that's all I can offer without seeing your system. Let me know if you need guidance on that. The point of failure is line 170 in VMATTBIOptimization.cs under the VMATTBICSIOptLoopMT project.

**Comment by adamblais** [comment]
I can't seem to reproduce this now! Closing
