### ISSUE TITLE
Introduction of Halcyon

### ISSUE THREAD

**Issue by fivey94** [esimiele/VMAT-TBI-CSI#20]
I've been working to get the Halcyon integration for the CSI code. I've managed to change the script enough to get it to recognize a Halcyon machine and input beams without any issues. 

However, Halcyons only have a 28 cm maximum field size (no jaws) compared to the standard linac's 40 cm field size. So an additional isocenter is required to fit the entire CSI PTV. 

I'm struggling to get the code to automatically introduce a 4th isocenter. I've made some changes to the code but I may need more insight than just what I can figure out on my own. 

I'm happy to share what I've done so far. Wasn't sure if I should add this as a pull request or an issue.

**Comment by esimiele** [comment]
Sure, I can take a look. If your code isn't working, I'd prefer you just share the code with me rather than opening a PR. Should be a pretty straight forward fix.
