### ISSUE TITLE
Optimization Loop: No plans found

### ISSUE THREAD

**Issue by adamblais** [esimiele/VMAT-TBI-CSI#22]
How does the optimization loop know which plan to optimize?

I have a test plan that I generated months ago. I added an iso and tweaked the beam setup and I'm trying to optimize it now but I just get "No plans found!". Tried making the course and plan names the same (Course VMAT TBI and Plan VMAT-TBI), but that doesn't help.

**Comment by esimiele** [comment]
It is searching for the plan to optimize based on the log output from the first script. It identifies the plans based on UID. If you copy the plan UID and paste it into the log file where it specifies plan UIDs for that patient, it should work. Look in the log_configuration.ini file in /bin/configuration to see where the log files are being written

**Comment by adamblais** [comment]
Great, thank you!

**Comment by adamblais** [comment]
closed
